### ISSUE TITLE
Python enviroment

### ISSUE THREAD

**Issue by MAHMOUDRR707** [nusnlp/LIF#3]
HI , I used this package using python 3.6  but I want to use it over any python environment , is there any updated repo ?  or what should change to fit the python 3.12

**Comment by linqian66** [comment]
Hi, thanks for your interest. What errors did you run into when using python 3.12? You may need to find out the package and code adjustment based on the errors shown, since older python packages and newer ones have their own dependencies.

**Comment by MAHMOUDRR707** [comment]
The error happened related to allennlp version

**Comment by MAHMOUDRR707** [comment]
@linqian66  specially when I try to run , wordtoknizer is not defined in new version nlp , if I tried to downgrade I would find another problem with huggingface_hub package requirements

**Comment by linqian66** [comment]
Hi, if you're still having trouble finding a working combination of packages on a different Python version, I would recommend using our tested environment configuration

**Comment by MAHMOUDRR707** [comment]
@linqian66 where is it please  ?

**Comment by linqian66** [comment]
in the README file: Python 3.6 and `requirements.txt` file for the packages

**Comment by MAHMOUDRR707** [comment]
@linqian66 I already have done that and working fine  but I just want to use 3.12 now due to my project , anyway thank you for your help and for this amazing project

**Comment by linqian66** [comment]
I see, since allennlp is no longer maintained, compatibility with Python 3.12 can be tricky. Rebuilding the code with PyTorch and HuggingFace's transformers packages is certainly an option, but it would be quite time-consuming. For this, you will need to check the allennlp configuration files and allennlp implementation code from your Python environment carefully, and extract relevant functions and rewrite them using the new packages.
